#Server Config
server:
  port: 8761 #default Eureka server port is also 8761

#Service Registry Config
eureka:
  client:
    register-with-eureka: false #Server will never register again with itself
    fetch-registry: false #Server don't need to fetch registry again

#Application Metadata
spring:
  application:
    name: service-registry
  zipkin:
    base-url: http://localhost:9411/
    

#Exposes actuator endpoints as mentioned @ https://docs.spring.io/spring-boot/docs/2.1.13.RELEASE/reference/html/production-ready-endpoints.html
management.endpoints.web.exposure.include: "*"
