#Server Config
server:
  port: 8551

#Service Registry Client Config (Moved to Config Server accessed at bootstrap through bootstrap.yaml config)
#eureka:
 # client:
  #  register-with-eureka: true #Service need to register with Eureka Server
   # fetch-registry: true #Service need to know what are all other services are available in the registry
    #serviceUrl:
     # defaultZone: http://localhost:8761/eureka
    #instance:
     # hostname: localhost

#Application Metadata
spring:
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://localhost:9411/
