#Common Service Registry Client Config Used in all Eureka Clients
eureka:
  client:
    register-with-eureka: true #API-GATEWAY also need to register with Eureka Server
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
